alter table public.profiles
  add column username text,
  add column avatar_path text,
  add column custom_instructions text not null default '',
  add column onboarding_completed boolean not null default false,
  add column theme text not null default 'black';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_username_format'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles add constraint profiles_username_format check (
      username is null or (
        username ~ '^[A-Za-z0-9_]{3,24}$'
        and lower(username) <> all (array[
          'admin', 'administrator', 'root', 'system', 'suporte', 'support',
          'moderador', 'moderator', 'lunatica', 'nitlabs', 'nitlabs_code'
        ])
      )
    );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_custom_instructions_length'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles add constraint profiles_custom_instructions_length
      check (char_length(custom_instructions) <= 2000);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_theme_valid'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles add constraint profiles_theme_valid
      check (theme in ('black', 'dark'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'messages_id_user_unique'
      and conrelid = 'public.messages'::regclass
  ) then
    alter table public.messages add constraint messages_id_user_unique unique (id, user_id);
  end if;
end $$;

create unique index profiles_username_lower_unique_idx
on public.profiles (lower(username))
where username is not null;

create table public.message_attachments (
  id uuid primary key default gen_random_uuid(),
  message_id uuid not null,
  conversation_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_path text not null unique,
  file_name text not null,
  mime_type text not null,
  size_bytes bigint not null,
  created_at timestamptz not null default now(),
  constraint message_attachments_message_owner_fk foreign key (message_id, user_id)
    references public.messages(id, user_id) on delete cascade,
  constraint message_attachments_conversation_owner_fk foreign key (conversation_id, user_id)
    references public.conversations(id, user_id) on delete cascade,
  constraint message_attachments_name_length check (char_length(file_name) between 1 and 160),
  constraint message_attachments_path_owner check (storage_path like user_id::text || '/%'),
  constraint message_attachments_size check (size_bytes between 1 and 5242880),
  constraint message_attachments_mime check (mime_type in (
    'image/jpeg', 'image/png', 'image/webp', 'image/gif',
    'application/pdf', 'text/plain', 'text/markdown', 'text/csv', 'application/json'
  ))
);

create index message_attachments_message_idx
on public.message_attachments (message_id);

create index message_attachments_conversation_created_idx
on public.message_attachments (conversation_id, created_at asc);

create index message_attachments_user_created_idx
on public.message_attachments (user_id, created_at desc);

create table public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  cost smallint not null default 1,
  attachment_count smallint not null default 0,
  created_at timestamptz not null default now(),
  constraint usage_events_cost check (cost between 1 and 5),
  constraint usage_events_attachment_count check (attachment_count between 0 and 4)
);

create index usage_events_user_created_idx
on public.usage_events (user_id, created_at desc);

alter table public.message_attachments enable row level security;
alter table public.usage_events enable row level security;

revoke all on table public.message_attachments, public.usage_events from anon, authenticated;
revoke all on sequence public.usage_events_id_seq from anon, authenticated;

grant select, insert, delete on table public.message_attachments to authenticated;

create policy "message_attachments_select_own"
on public.message_attachments for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "message_attachments_insert_own"
on public.message_attachments for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "message_attachments_delete_own"
on public.message_attachments for delete
to authenticated
using ((select auth.uid()) = user_id);

create policy "usage_events_deny_client_access"
on public.usage_events for all
to authenticated
using (false)
with check (false);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars',
  'avatars',
  false,
  3145728,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'attachments',
  'attachments',
  false,
  5242880,
  array[
    'image/jpeg', 'image/png', 'image/webp', 'image/gif',
    'application/pdf', 'text/plain', 'text/markdown', 'text/csv', 'application/json'
  ]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "avatars_select_own"
on storage.objects for select
to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);

create policy "avatars_insert_own"
on storage.objects for insert
to authenticated
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);

create policy "avatars_update_own"
on storage.objects for update
to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text)
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);

create policy "avatars_delete_own"
on storage.objects for delete
to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);

create policy "attachments_select_own"
on storage.objects for select
to authenticated
using (bucket_id = 'attachments' and (storage.foldername(name))[1] = (select auth.uid())::text);

create policy "attachments_insert_own"
on storage.objects for insert
to authenticated
with check (bucket_id = 'attachments' and (storage.foldername(name))[1] = (select auth.uid())::text);

create policy "attachments_update_own"
on storage.objects for update
to authenticated
using (bucket_id = 'attachments' and (storage.foldername(name))[1] = (select auth.uid())::text)
with check (bucket_id = 'attachments' and (storage.foldername(name))[1] = (select auth.uid())::text);

create policy "attachments_delete_own"
on storage.objects for delete
to authenticated
using (bucket_id = 'attachments' and (storage.foldername(name))[1] = (select auth.uid())::text);
