create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create type public.message_role as enum ('user', 'assistant', 'system');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_display_name_length check (char_length(display_name) <= 80)
);

create table public.conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Nova conversa',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint conversations_title_length check (char_length(title) between 1 and 80),
  constraint conversations_id_user_unique unique (id, user_id)
);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.message_role not null,
  content text not null,
  created_at timestamptz not null default now(),
  constraint messages_content_length check (char_length(content) between 1 and 50000),
  constraint messages_conversation_owner_fk foreign key (conversation_id, user_id)
    references public.conversations(id, user_id) on delete cascade
);

create table public.rate_limits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index conversations_user_updated_idx on public.conversations (user_id, updated_at desc);
create index conversations_user_created_idx on public.conversations (user_id, created_at desc);
create index messages_conversation_created_idx on public.messages (conversation_id, created_at asc);
create index messages_user_idx on public.messages (user_id);
create index rate_limits_user_created_idx on public.rate_limits (user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.rate_limits enable row level security;

revoke all on table public.profiles, public.conversations, public.messages, public.rate_limits from anon, authenticated;
revoke all on sequence public.rate_limits_id_seq from anon, authenticated;

grant select, update on table public.profiles to authenticated;
grant select, insert, update, delete on table public.conversations to authenticated;
grant select, insert, update, delete on table public.messages to authenticated;

create policy "profiles_select_own"
on public.profiles for select
to authenticated
using ((select auth.uid()) = id);

create policy "profiles_update_own"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "conversations_select_own"
on public.conversations for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "conversations_insert_own"
on public.conversations for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "conversations_update_own"
on public.conversations for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "conversations_delete_own"
on public.conversations for delete
to authenticated
using ((select auth.uid()) = user_id);

create policy "messages_select_own"
on public.messages for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "messages_insert_own"
on public.messages for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "messages_update_own"
on public.messages for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "messages_delete_own"
on public.messages for delete
to authenticated
using ((select auth.uid()) = user_id);

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function private.set_updated_at();

create trigger conversations_set_updated_at
before update on public.conversations
for each row execute function private.set_updated_at();

create or replace function private.touch_conversation()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  update public.conversations
  set updated_at = now()
  where id = coalesce(new.conversation_id, old.conversation_id)
    and user_id = coalesce(new.user_id, old.user_id);
  return coalesce(new, old);
end;
$$;

create trigger messages_touch_conversation
after insert or update or delete on public.messages
for each row execute function private.touch_conversation();

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    left(coalesce(nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''), split_part(coalesce(new.email, ''), '@', 1), 'Usuário'), 80)
  );
  return new;
end;
$$;

revoke all on function private.handle_new_user() from public, anon, authenticated;
revoke all on function private.set_updated_at() from public, anon, authenticated;
revoke all on function private.touch_conversation() from public, anon, authenticated;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();
