-- LunaMax is activated with manually issued, high-entropy codes. The browser
-- never reads the code inventory and only active plans are visible to owners.
create table public.plan_codes (
  id uuid primary key default gen_random_uuid(),
  code_hash text not null unique,
  duration_days smallint not null default 30,
  max_redemptions smallint not null default 1,
  redemption_count smallint not null default 0,
  active boolean not null default true,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  constraint plan_codes_hash_format check (code_hash ~ '^[0-9a-f]{64}$'),
  constraint plan_codes_duration check (duration_days between 1 and 365),
  constraint plan_codes_redemption_limit check (max_redemptions between 1 and 1000),
  constraint plan_codes_redemption_count check (redemption_count between 0 and max_redemptions)
);

create table public.user_plans (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan text not null default 'lunamax',
  status text not null default 'active',
  source text not null default 'manual_code',
  activated_at timestamptz not null default now(),
  expires_at timestamptz not null,
  updated_at timestamptz not null default now(),
  constraint user_plans_plan_valid check (plan = 'lunamax'),
  constraint user_plans_status_valid check (status in ('active', 'expired')),
  constraint user_plans_source_valid check (source = 'manual_code')
);

create table public.plan_redemptions (
  id bigint generated by default as identity primary key,
  code_id uuid not null references public.plan_codes(id) on delete restrict,
  user_id uuid not null references auth.users(id) on delete cascade,
  redeemed_at timestamptz not null default now(),
  unique (code_id, user_id)
);

create index user_plans_active_expiry_idx
on public.user_plans (status, expires_at desc);

create index plan_redemptions_user_idx
on public.plan_redemptions (user_id, redeemed_at desc);

alter table public.plan_codes enable row level security;
alter table public.user_plans enable row level security;
alter table public.plan_redemptions enable row level security;

revoke all on table public.plan_codes, public.user_plans, public.plan_redemptions from anon, authenticated;
revoke all on sequence public.plan_redemptions_id_seq from anon, authenticated;
grant select on table public.user_plans to authenticated;

create policy "user_plans_select_own"
on public.user_plans for select
to authenticated
using ((select auth.uid()) = user_id);

-- The two inventory tables deliberately have no client policies. Only the
-- service role inside the redemption Edge Function can access them.
create policy "plan_codes_deny_client_access"
on public.plan_codes for all
to authenticated
using (false)
with check (false);

create policy "plan_redemptions_deny_client_access"
on public.plan_redemptions for all
to authenticated
using (false)
with check (false);

create or replace function public.redeem_lunamax_code(p_user_id uuid, p_code_hash text)
returns table (plan text, status text, activated_at timestamptz, expires_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
declare
  selected_code public.plan_codes%rowtype;
  current_expiry timestamptz;
  next_expiry timestamptz;
begin
  if p_user_id is null or p_code_hash !~ '^[0-9a-f]{64}$' then
    raise exception using errcode = 'P0001', message = 'invalid_code';
  end if;

  select * into selected_code
  from public.plan_codes
  where code_hash = p_code_hash
    and active = true
    and redemption_count < max_redemptions
    and (expires_at is null or expires_at > now())
  for update;

  if not found then
    raise exception using errcode = 'P0001', message = 'invalid_code';
  end if;

  if exists (
    select 1 from public.plan_redemptions
    where code_id = selected_code.id and user_id = p_user_id
  ) then
    raise exception using errcode = 'P0001', message = 'code_already_used';
  end if;

  select up.expires_at into current_expiry
  from public.user_plans as up
  where up.user_id = p_user_id and up.status = 'active' and up.expires_at > now()
  for update;

  next_expiry := greatest(coalesce(current_expiry, now()), now())
    + make_interval(days => selected_code.duration_days);

  insert into public.plan_redemptions (code_id, user_id)
  values (selected_code.id, p_user_id);

  update public.plan_codes
  set redemption_count = redemption_count + 1
  where id = selected_code.id;

  insert into public.user_plans (user_id, plan, status, source, activated_at, expires_at, updated_at)
  values (p_user_id, 'lunamax', 'active', 'manual_code', now(), next_expiry, now())
  on conflict (user_id) do update set
    plan = excluded.plan,
    status = excluded.status,
    source = excluded.source,
    expires_at = excluded.expires_at,
    updated_at = now();

  return query
  select up.plan, up.status, up.activated_at, up.expires_at
  from public.user_plans as up
  where up.user_id = p_user_id;
end;
$$;

revoke all on function public.redeem_lunamax_code(uuid, text) from public, anon, authenticated;
grant execute on function public.redeem_lunamax_code(uuid, text) to service_role;

create trigger user_plans_set_updated_at
before update on public.user_plans
for each row execute function private.set_updated_at();

alter table public.memories drop constraint memories_category_valid;
alter table public.memories add constraint memories_category_valid
  check (category in ('identity', 'education', 'work', 'preference', 'personal', 'project', 'goal', 'custom'));

alter table public.usage_events drop constraint usage_events_cost;
alter table public.usage_events add constraint usage_events_cost check (cost between 1 and 10);
alter table public.usage_events drop constraint usage_events_attachment_count;
alter table public.usage_events add constraint usage_events_attachment_count check (attachment_count between 0 and 3);
